config/routes.rb
Rails.application.routes.draw do
  get 'shapes/show'

  get 'numbers/show'

  get 'days/show'

  get 'colors/show'

  get 'bodyparts/show'

  get 'aupper/show'

  get 'alower/show'

  resources :users
  resources :students
  resources :alower, :aupper, :bodyparts, :colors, :days, :numbers, :shapes

  resource :sessions
  root 'users#index'
end

app/models/alower.rb
class Alowers < ActiveRecord::Base
  belongs_to :student
end

app/models/aupper.rb
class Auppers < ActiveRecord::Base
  belongs_to :student
end

app/models/body_parts.rb
class BodyParts < ActiveRecord::Base
  belongs_to :student
end

app/models/colors.rb
class Colors < ActiveRecord::Base
  belongs_to :student
end

app/models/days.rb
class Days < ActiveRecord::Base
  belongs_to :student
end

app/models/numbers.rb
class Numbers < ActiveRecord::Base
  belongs_to :student
end

app/models/shapes.rb
class Shapes<ActiveRecord::Base
  belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  has_one :alower
  has_one :aupper
  has_one :bodyparts
  has_one :colors
  has_one :days
  has_one :numbers
  has_one :shapes
end

app/models/user.rb
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
class User < ActiveRecord::Base
  has_many :students
  # validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  # uniqueness:  { case_sensitive: false }
  validates :password, presence: true
  validates :username, presence: true, uniqueness: true
  has_secure_password

  if Rails.env.production?

    validates_presence_of :password, :on => :create
    validates_confirmation_of :password
    validates_presence_of :password

  end
end

app/controllers/alower_controller.rb
class AlowerController < ApplicationController
  def show
  end
end

app/controllers/aupper_controller.rb
class AupperController < ApplicationController
  def show
  end
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  def show
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    p "def new users controller hit"
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:current_user_id] = user.id
      session[:filter] = "mostRecent"
      redirect_to root_path
    else
      flash[:error] = user.errors.full_messages
      redirect_to root_path
    end
  end

  def show
    if params[:id] == current_user.id.to_s
      @user = current_user
      @notes = @user.notes
      session[:filter] = "user"
    else
      flash[:error] = "You don't have access to that profile"

      redirect_to current_user
    end
  end

  def user_params
    params.require(:user).permit(:password, :first_name, :last_name, :username)
  end

end

app/helpers/alower_helper.rb
module AlowerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def signed_in?
    session[:current_user_id]
  end

  def avatar_url
    gravatar_id = Digest::MD5.hexdigest(current_user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png}"
  end
end

app/helpers/aupper_helper.rb
module AupperHelper
end

app/helpers/bodyparts_helper.rb
module BodypartsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/numbers_helper.rb
module NumbersHelper
end

app/helpers/shapes_helper.rb
module ShapesHelper
end

app/views/users/_sign_in.html.erb
<div id="myModalIn" class="reveal-modal small"  data-reveal>
   <%= form_for "session", url: sessions_path, :method=> :post, html: {class: "signin"} do |f|%>
    <%= f.label :username  %>
    <%= f.text_field :username, class: "form-control"  %>
    <br>
    <%= f.label :password  %>
    <%= f.password_field :password, class: "form-control" %>
    <br>
    <a href="#"><%= f.submit :SignIn, class: "button expand" %></a>
  <% end %>
  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/users/_sign_up.html.erb
<div id="myModalUp" class="reveal-modal small" data-reveal>
  <%= form_for @user, url: users_path, :method=> :post, html: {class: "signup"} do |f|%>

    <%= f.label :username  %>
    <%= f.text_field :username, class: "form-control", placeholder: "Choose a Username" %>
    <br>
    <%= f.label :password  %>
    <%= f.password_field :password, class: "form-control", placeholder: "Create a Password" %>
    <br>
    <a href="#"><%= f.submit :SignUp, class: "button expand" %></a>
  <% end %>
  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/users/_students.html.erb
<div id="myModalStudents" class="reveal-modal" data-reveal>
  <% if session[:current_user_id] != nil %>
    <% @user_id = session[:current_user_id] %>
    <% @user = User.find(@user_id) %>
    <% @students = @user.students %>
    <% @students.each do |s| %>
      <%=link_to "#{s.first_name}, #{s.last_name}", student_path(s.id)%>
      <br>
    <% end %>
  <%end%>
  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/users/index.html.erb
<%= render "sign_in" %>
<%= render "shared/nav" %>
<%= render "sign_up" %>
<% if session[:current_user_id] != nil %>
<%= render "students" %>
<%= render "students/add_student" %>
<%end%>